### ISSUE TITLE
Allow editing a cron expression, already generated previously

### ISSUE THREAD

**Issue by JossyDevers** [JossyDevers/cron-expression-input#1]
Right now in the component you can generate a cron expression or paste one, but you must also be able to edit one after generating or pasting it.

In the sense that if there is already a cron expression in the component's input, when opening the creation modal, the fields of the modal must be able to be automatically completed with the values ​​of the input cron expression.

**Comment by alexandis** [comment]
I wanted to report the same issue and see it's already here and it's the only issue for the moment :-D
Is there a way to fine-tune the given control by our own to achieve this goal? If the cron setting is very complex - it's frustrating to see inability to tune the saved value... Or at least - when are you planning to introduce the enhancement? Thanx.

**Comment by JossyDevers** [comment]
Hello @alexandis, I have made the improvement, I will be publishing the component real soon.

**Comment by alexandis** [comment]
Hi. Great - I've installed a new version. But... how to use it in my Angular app??

**Comment by alexandis** [comment]
Hello? Could you please follow up?
