### ISSUE TITLE
Cron-expression-input could be an optional input

### ISSUE THREAD

**Issue by alexandis** [JossyDevers/cron-expression-input#2]
Now it always complains, if the Cron field is not filled. But it could be an optional component. Please add more parameters (css class - not only a color value to set up UI, inner objects access, like input field to fine-tune it, etc).

**Comment by JossyDevers** [comment]
Several attributes were added to provide customizable functionality to the component.
Added support for a form submit event to validate input.

Added Attributes:

required="true" -> Allow component to ship empty.
hotValidate="true" -> Enable validation while writing the component, if it is set to false, it will only be validated when the submit event is performed within a form.
value="4 2 10,20 4-8 0,2" -> Allow to set a default value on the component.

**Hello @alexandis, I have made the improvement, I will be publishing the component real soon.**
